### ISSUE TITLE
Suggestion - Allow Custom Heads in StartPage.yml

### ISSUE THREAD

**Issue by BirminghamBoy** [7sat/DynamicShop3#82]
See the above title - currently, adding skull data to the StartPage.yml does not change the button item (however, it does work when editing items within a shop). 

Below is the text I tried to use in StartPage.yml:

```
  icon: PLAYER_HEAD
  itemStack:
    ==: ItemMeta
    meta-type: SKULL
    internal: H4sIAAAAAAAA/+NiYOBgYPJMYVAxNzJOsTA1N9c1SEox1jVOTDbXTTJITtE1MTGyMLYwTzIxMkhmAAAapQSXLwAAAA==
    skull-owner:
      ==: PlayerProfile
      uniqueId: 723d8577-0bd3-3ac7-b0cd-4428387b420c
      name: Enqie
      properties:
      - name: textures
        value: ewogICJ0aW1lc3RhbXAiIDogMTY1MTU4MDYwNTE2OCwKICAicHJvZmlsZUlkIiA6ICJkNmZlODBhOWMyNjA0YjRlOGY0NTRhYjBhZWIzOGNhNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJFbnFpZSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80ZmYxMzNhY2FkYjQ2NDUyYWUxZjczNDAyNWU0ZjNmZGRjZTYxMzg1ZTU2NjRkNzI5N2FhOTY1NTdlZGMzYzVlIiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyIKICAgIH0KICB9Cn0=
```
